// General
export const APP_LOADED = 'APP_LOADED'
export const ASYNC_START = 'ASYNC_START'
export const REDIRECT = 'REDIRECT'
export const JUMPSTART = 'JUMPSTART'
export const CLEAN_ERROR = 'CLEAN_ERROR'

// Auth
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const AUTH_PAGE_UNLOADED = 'AUTH_PAGE_UNLOADED'

// Home
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED'
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED'
export const ALLOW_EDIT_ARTICLES = 'ALLOW_EDIT_ARTICLES'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'

// ArticleEditor
export const ARTICLE_EDITOR_PAGE_LOADED = 'ARTICLE_EDITOR_PAGE_LOADED'
export const UPDATE_FIELD_ARTICLE_EDITOR = 'UPDATE_FIELD_ARTICLE_EDITOR'
export const ARTICLE_EDITOR_PAGE_UNLOADED = 'ARTICLE_EDITOR_PAGE_UNLOADED'
export const SUBMIT_ARTICLE = 'SUBMIT_ARTICLE'

// Companies
export const COMPANIES_PAGE_LOADED = 'COMPANIES_PAGE_LOADED'
export const COMPANIES_PAGE_SEARCH_LOADED = 'COMPANIES_PAGE_SEARCH_LOADED'
export const COMPANIES_PAGE_TAG_LOADED = 'COMPANIES_PAGE_TAG_LOADED'
export const COMPANIES_PAGE_UNLOADED = 'COMPANIES_PAGE_UNLOADED'
export const ALLOW_EDIT_COMPANIES = 'ALLOW_EDIT_COMPANIES'
export const DELETE_COMPANY = 'DELETE_COMPANY'
export const VIEW_COMPANY_RECORDS = 'VIEW_COMPANY_RECORDS'

// CompanyEditor
export const COMPANY_EDITOR_PAGE_LOADED = 'COMPANY_EDITOR_PAGE_LOADED'
export const UPDATE_FIELD_COMPANY_EDITOR = 'UPDATE_FIELD_COMPANY_EDITOR'
export const SUBMIT_COMPANY = 'SUBMIT_COMPANY'
export const COMPANY_EDITOR_PAGE_UNLOADED = 'COMPANY_EDITOR_PAGE_UNLOADED'
export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'

// Records
export const RECORDS_PAGE_LOADED = 'RECORDS_PAGE_LOADED'
export const RECORDS_PAGE_UNLOADED = 'RECORDS_PAGE_UNLOADED'
export const ALLOW_EDIT_RECORDS = 'ALLOW_EDIT_RECORDS'
export const DELETE_RECORD = 'DELETE_RECORD'

// RecordEditor
export const RECORD_EDITOR_PAGE_LOADED = 'RECORD_EDITOR_PAGE_LOADED'
export const UPDATE_FIELD_RECORD_EDITOR = 'UPDATE_FIELD_RECORD_EDITOR'
export const SUBMIT_RECORD = 'SUBMIT_RECORD'
export const RECORD_EDITOR_PAGE_UNLOADED = 'RECORD_EDITOR_PAGE_UNLOADED'
export const REMOVE_KEY = 'REMOVE_KEY'
export const TOGGLE_PLAN = 'TOGGLE_PLAN'

// Sodium
export const SWITCH_SODIUM = 'SWITCH_SODIUM'
export const SELECT_COMPANY = 'SELECT_COMPANY'
export const LOAD_SODIUM = 'LOAD_SODIUM'
export const UNLOAD_SODIUM = 'UNLOAD_SODIUM'
