// General
export const APP_LOADED = 'APP_LOADED'
export const ASYNC_START = 'ASYNC_START'
export const REDIRECT = 'REDIRECT'
export const JUMPSTART = 'JUMPSTART'
export const CLEAN_ERROR = 'CLEAN_ERROR'

// Auth
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const AUTH_PAGE_UNLOADED = 'AUTH_PAGE_UNLOADED'

// Home
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED'
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED'
export const ALLOW_EDIT_ARTICLE = 'ALLOW_EDIT_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'

// ArticleEditor
export const ARTICLE_EDITOR_PAGE_LOADED = 'ARTICLE_EDITOR_PAGE_LOADED'
export const UPDATE_FIELD_ARTICLE_EDITOR = 'UPDATE_FIELD_ARTICLE_EDITOR'
export const ARTICLE_EDITOR_PAGE_UNLOADED = 'ARTICLE_EDITOR_PAGE_UNLOADED'
export const SUBMIT_ARTICLE = 'SUBMIT_ARTICLE'
